const state={library:[],settings:{},status:{},selected:null,page:'home',query:'',diagnostics:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const api=async(path,opts={})=>{const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});let j;try{j=await r.json()}catch{throw new Error(`Resposta inválida (${r.status})`)}if(!r.ok||(j?.ok===false&&!j?.cancelled))throw new Error(j?.error||`HTTP ${r.status}`);return j};
const post=(p,b={})=>api(p,{method:'POST',body:JSON.stringify(b)});
const fmtBytes=n=>{if(!n)return'--';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i>1?1:0)} ${u[i]}`};
const fmtTime=s=>{if(!s)return'0h';const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h}h ${m}m`:`${m}m`};
const hue=id=>[220,258,280,330,190,25,145][parseInt((id||'1').slice(0,2),16)%7];
const escapeHtml=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg,error=false){const t=$('#toast');t.textContent=msg;t.className='toast show'+(error?' error':'');clearTimeout(t._timer);t._timer=setTimeout(()=>t.className='toast',3800)}
function empty(text='Nenhum jogo importado ainda.'){return`<div class="empty"><div><b>${text}</b>Use “Importar Jogo” ou “Escanear CUSA” para adicionar seus próprios dumps.</div></div>`}
function card(g,small=false){const art=g.icon?`<img src="${g.icon}" alt="">`:`<span class="game-symbol">${g.platform==='PS4'?'▣':'🎮'}</span>`;const badge=g.cusa?`<span class="cusa-badge">${escapeHtml(g.title_id)}</span>`:'';return `<article class="${small?'recent-card':'game-card'}" data-game="${g.id}" style="--h:${hue(g.id)}"><div class="game-art">${art}</div>${badge}${g.favorite?'<span class="favorite-mark">♥</span>':''}${small?`<span class="playtime">◷ ${fmtTime(g.play_seconds)}</span>`:''}<div class="game-label"><strong>${escapeHtml(g.title)}</strong><small>${escapeHtml(g.title_id||g.platform||g.kind)}</small></div></article>`}
function filtered(list=state.library){const q=state.query.trim().toLowerCase();return q?list.filter(g=>`${g.title} ${g.title_id} ${g.content_id} ${g.platform} ${g.region}`.toLowerCase().includes(q)):list}
function renderLibrary(){const all=filtered();$('#libraryGrid').innerHTML=all.length?all.map(g=>card(g)).join(''):empty();const rec=filtered([...state.library].filter(g=>g.last_played).sort((a,b)=>b.last_played-a.last_played));$('#recentGrid').innerHTML=rec.length?rec.map(g=>card(g)).join(''):empty('Nenhuma execução registrada.');const fav=filtered(state.library.filter(g=>g.favorite));$('#favoriteGrid').innerHTML=fav.length?fav.map(g=>card(g)).join(''):empty('Nenhum favorito ainda.');const homeLibrary=$('#homeLibrary');if(homeLibrary)homeLibrary.innerHTML=all.length?all.slice(0,5).map(g=>card(g)).join(''):empty();$('#homeRecent').innerHTML=rec.length?rec.slice(0,5).map(g=>card(g,true)).join(''):empty('Jogue algo para aparecer aqui.');$$('[data-game]').forEach(el=>el.onclick=()=>openGame(el.dataset.game))}
function vulkanGpus(){return state.status?.vulkan?.gpus||[]}
function renderGpuOptions(){const select=$('#gpuIndex');if(!select)return;const current=String(state.settings.gpu_index??-1);const gpus=vulkanGpus();select.innerHTML='<option value="-1">Auto — melhor GPU + tuning automático</option>'+gpus.map(g=>`<option value="${g.index}">GPU ${g.index} — ${escapeHtml(g.name)} · ${escapeHtml(g.architecture||g.type)}</option>`).join('');select.value=[...select.options].some(o=>o.value===current)?current:'-1';updateGpuHint()}
function updateGpuHint(){const hint=$('#gpuHint'),auto=$('#autoTuningStatus'),idx=Number($('#gpuIndex')?.value??-1),g=vulkanGpus().find(x=>Number(x.index)===idx),best=g||vulkanGpus().find(x=>x.shadps4_ready&&x.type==='Dedicada')||vulkanGpus().find(x=>x.type==='Dedicada')||vulkanGpus()[0];if(!hint)return;if(!g){const ready=vulkanGpus().filter(x=>x.shadps4_ready);hint.textContent=vulkanGpus().length?`Auto escolhe GPU dedicada/compatível e aplica política por arquitetura. ${ready.length}/${vulkanGpus().length} adaptador(es) atendem o caminho PS4.`:'Nenhum adaptador enumerado. O driver Vulkan precisa expor uma GPU ao loader.'}else{const t=g.tuning||{};hint.textContent=`${g.name} • ${g.architecture||'Vulkan'} • Vulkan ${g.api_version} • ${fmtBytes(g.vram)} • alvo de residência ~${Math.round((t.target_ratio||0)*100)}%`};if(auto){if(!best){auto.textContent='Auto tuning aguardando uma GPU Vulkan.'}else{const t=best.tuning||{};auto.textContent=`Automático: ${best.architecture||'Vulkan'} · descriptor cache ${t.descriptor_cache_entries||'auto'} · pipeline em background · uploads sem stall · VRAM alvo ~${Math.round((t.target_ratio||0)*100)}% (${fmtBytes(t.target||0)}) · ajuste nativo por VK_EXT_memory_budget quando disponível.`}}}
function renderVulkanAdapters(){const box=$('#vulkanAdapters');if(!box)return;const vk=state.status.vulkan||{},gpus=vk.gpus||[];if(!gpus.length){box.innerHTML=`<div class="vulkan-card bad"><div><small>Vulkan</small><b>Nenhuma GPU enumerada</b></div><span>${escapeHtml(vk.error||'Loader/driver não respondeu ao probe.')}</span></div>`;return}box.innerHTML=gpus.map(g=>{const t=g.tuning||{},target=Math.round((t.target_ratio||0)*100);return `<div class="vulkan-card ${g.shadps4_ready?'ok':'warn'}"><div class="vk-head"><span class="gpu-index">GPU ${g.index}</span><b>${escapeHtml(g.name)}</b></div><div class="vk-spec"><span>${escapeHtml(g.architecture||g.type)}</span><span>Vulkan ${escapeHtml(g.api_version)}</span><span>${fmtBytes(g.vram)}</span><span>VRAM alvo ${target}% · ${fmtBytes(t.target||0)}</span></div><div class="vk-ext"><i class="${g.swapchain?'yes':'no'}">swapchain</i><i class="${g.push_descriptor?'yes':'no'}">push descriptor</i><i class="${g.memory_budget?'yes':'no'}">memory budget</i><i class="${g.pipeline_cache_control?'yes':'no'}">pipeline control</i><i class="${g.shadps4_ready?'yes':'no'}">shadPS4 ${g.shadps4_ready?'ready':'check'}</i></div><small class="muted">${escapeHtml(g.translation_path||'Guest → SPIR-V → Vulkan → driver')}</small></div>`}).join('')}
function renderStatus(){const s=state.status,total=s.ram_total||0,used=s.ram_used||0,ram=total?Math.round(used/total*100):0,disk=s.disk_total?Math.round(s.disk_used/s.disk_total*100):0;$('#cpuGauge').textContent=`${s.cpu_threads||'--'}T`;$('#ramGauge').textContent=total?`${ram}%`:'--';$('#diskGauge').textContent=s.disk_total?`${disk}%`:'--';$('.gauge:nth-child(1) .gauge-ring')?.style.setProperty('--p',Math.min(100,(s.cpu_threads||8)*4));$('.gauge:nth-child(2) .gauge-ring')?.style.setProperty('--p',ram);$('.gauge:nth-child(3) .gauge-ring')?.style.setProperty('--p',disk);$('#storageText').textContent=`${fmtBytes(s.disk_used)} / ${fmtBytes(s.disk_total)}`;$('#storageBar').style.width=`${disk}%`;const cores=[];if(s.engines?.kyty)cores.push('PS5');if(s.engines?.shadps4)cores.push('PS4');$('#coreStatusText').textContent=cores.length?`Core ${cores.join(' + ')} pronto`:'Core não compilado/configurado';const active=Object.keys(s.active_processes||{}).length,cache=s.pipeline_cache||{},vk=s.vulkan||{},ready=(vk.gpus||[]).filter(g=>g.shadps4_ready).length;const items=[['CPU',s.cpu_name||'Desconhecida',`${s.cpu_threads||'?'} threads`],['RAM',fmtBytes(s.ram_total),`${fmtBytes(s.ram_used)} em uso`],['Vulkan',s.vulkan_runtime?`Loader ${vk.loader_version||'pronto'}`:'Runtime não utilizável',`${(vk.gpus||[]).length} GPU(s), ${ready} pronta(s) para PS4`],['Auto GPU',((vk.gpus||[]).find(g=>g.type==='Dedicada')||vk.gpus?.[0])?.architecture||'Aguardando GPU','IR → SPIR-V → Vulkan + tuning automático'],['Cache Vulkan',fmtBytes(cache.size||0),`${cache.files||0} arquivo(s) encontrado(s)`],['KytyPS5',s.engines?.kyty?'Encontrado':'Não encontrado',s.engines?.kyty||'Configure o executável'],['shadPS4',s.engines?.shadps4?'Encontrado':'Não configurado',s.engines?.shadps4||'Necessário para CUSA/PS4'],['CUSA',`${state.library.filter(g=>g.cusa).length} título(s)`,`Serial + versão + região integrados`],['Processos',active?`${active} em execução`:'Nenhum ativo',active?'Monitorando exit code e tempo':'Pronto'],['Disco',fmtBytes(s.disk_total),`${disk}% usado`]];$('#diagnosticCards').innerHTML=items.map(([a,b,c])=>`<div class="diag-card"><small>${escapeHtml(a)}</small><b>${escapeHtml(b)}</b><span>${escapeHtml(c)}</span></div>`).join('');renderGpuOptions();renderVulkanAdapters()}
function showPage(name){state.page=name;$$('.page').forEach(p=>p.classList.remove('active'));$(`#page-${name}`)?.classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(name==='system')loadLogs();window.scrollTo({top:0,behavior:'smooth'})}
async function refresh(){try{const [lib,sett,status]=await Promise.all([api('/api/library'),api('/api/settings'),api('/api/status')]);state.library=lib;state.settings=sett;state.status=status;fillSettings();renderLibrary();renderStatus()}catch(e){toast(e.message,true)}}
function fillSettings(){const s=state.settings;$('#kytyPath').value=s.kyty_path||'';$('#shadPath').value=s.shadps4_path||'';$('#performanceProfile').value=s.performance_profile||'balanced';$('#presentMode').value=s.present_mode||'Fifo';$('#shaderOpt').value=s.shader_optimization||'Performance';$('#resolution').value=s.resolution||'1280x720';$('#vblankFrequency').value=s.vblank_frequency||60;$('#fullscreen').checked=!!s.fullscreen;$('#redzone').checked=s.redzone!==false;$('#playgoHack').checked=!!s.playgo_hack;$('#ps4BootMode').value=s.ps4_boot_mode||'auto';$('#playerName').value=s.player_name||'Player1';$('#profileName').textContent=s.player_name||'Player1';const heroName=$('#heroName');if(heroName)heroName.textContent=s.player_name||'Player1';updateProfileHint();renderGpuOptions()}
async function saveSettings(){try{const body={kyty_path:$('#kytyPath').value.trim(),shadps4_path:$('#shadPath').value.trim(),performance_profile:$('#performanceProfile').value,present_mode:$('#presentMode').value,shader_optimization:$('#shaderOpt').value,resolution:$('#resolution').value,vblank_frequency:Number($('#vblankFrequency').value),fullscreen:$('#fullscreen').checked,redzone:$('#redzone').checked,playgo_hack:$('#playgoHack').checked,gpu_index:Number($('#gpuIndex').value),player_name:$('#playerName').value.trim()||'Player1',ps4_boot_mode:$('#ps4BootMode').value};const r=await post('/api/settings',body);state.settings=r.settings;fillSettings();state.status=await api('/api/status');renderStatus();toast('Configurações CUSA/Vulkan salvas.')}catch(e){toast(e.message,true)}}
const profiles={stable:{present:'Fifo',shader:'None',resolution:'1280x720',vblank:60,redzone:true,playgo:false,hint:'Prioriza compatibilidade e frame pacing. Ideal para primeiro boot.'},balanced:{present:'Fifo',shader:'Performance',resolution:'1280x720',vblank:60,redzone:true,playgo:false,hint:'Equilíbrio entre estabilidade, cache e FPS. Recomendado.'},turbo:{present:'Mailbox',shader:'Performance',resolution:'960x540',vblank:60,redzone:true,playgo:false,hint:'Reduz carga de GPU e tenta menor latência. Mailbox só é usado se a GPU/driver suportar.'},custom:{hint:'Ajustes manuais. O silício não lê pensamentos, infelizmente.'}};
function updateProfileHint(){const p=profiles[$('#performanceProfile')?.value]||profiles.custom;const el=$('#profileHint');if(el)el.textContent=p.hint}
function applyProfile(){const name=$('#performanceProfile').value,p=profiles[name]||profiles.custom;if(name==='custom')return updateProfileHint();$('#presentMode').value=p.present;$('#shaderOpt').value=p.shader;$('#resolution').value=p.resolution;$('#vblankFrequency').value=p.vblank;$('#redzone').checked=p.redzone;$('#playgoHack').checked=p.playgo;updateProfileHint();toast(`Preset ${name==='stable'?'Estável':name==='balanced'?'Balanceado':'Turbo'} aplicado. Salve para persistir.`)}
async function runDiagnostics(){try{const r=await api('/api/diagnostics');state.diagnostics=r.checks||[];$('#diagnosticChecks').innerHTML=state.diagnostics.map(x=>`<div class="check-card ${x.ok?'ok':'bad'}"><b>${x.ok?'✓':'!'} ${escapeHtml(x.name)}</b><span>${escapeHtml(x.detail)}</span></div>`).join('');state.status=r.status||state.status;renderStatus();toast(state.diagnostics.every(x=>x.ok)?'Diagnóstico concluído sem bloqueios.':'Diagnóstico encontrou requisitos ausentes.',!state.diagnostics.every(x=>x.ok))}catch(e){toast(e.message,true)}}
async function probeVulkan(){try{const vk=await api('/api/vulkan');state.status.vulkan=vk;state.status.vulkan_runtime=!!vk.available;renderStatus();toast(vk.gpus?.length?`Vulkan: ${vk.gpus.length} adaptador(es) enumerado(s).`:vk.error||'Nenhuma GPU Vulkan encontrada.',!vk.gpus?.length)}catch(e){toast(e.message,true)}}
async function openPipelineCache(){try{const r=await post('/api/open-pipeline-cache');toast(`Cache Vulkan: ${r.path}`)}catch(e){toast(e.message,true)}}
async function doImport(kind='file'){location.href='/import.html'}
async function scanCusa(){try{toast('Escaneando raiz por títulos PS4…');const r=await post('/api/scan-cusa',{});if(r.cancelled)return;await refresh();showPage('library');toast(`${r.count} título(s) PS4 encontrado(s).`)}catch(e){toast(e.message,true)}}
function openGame(id){const g=state.library.find(x=>x.id===id);if(!g)return;state.selected=g;$('#modalTitle').textContent=g.title;$('#modalPlatform').textContent=`${g.platform} • ${String(g.kind).toUpperCase()}${g.cusa?' • CUSA':''}`;$('#modalMeta').textContent=[g.title_id,g.content_id,g.path].filter(Boolean).join('  •  ');const details=[['Versão',g.app_ver],['Região',g.region],['Sistema',g.system_ver],['Categoria',g.category],['Entradas PKG',g.pkg_entries],['PFS',g.pkg_pfs_size?fmtBytes(g.pkg_pfs_size):'']].filter(([,v])=>v);$('#modalDetails').innerHTML=details.map(([k,v])=>`<span><small>${escapeHtml(k)}</small><b>${escapeHtml(v)}</b></span>`).join('');$('#modalStatus').textContent=g.status||'Pronto';$('#modalProfile').value=g.profile_override||'global';$('#modalFavorite').textContent=g.favorite?'♥ Favorito':'♡ Favoritar';$('#modalPoster').innerHTML=g.icon?`<img src="${g.icon}" alt="">`:'🎮';const isPS4=String(g.platform).toUpperCase()==='PS4';$('#modalBootRow').style.display=isPS4&&g.kind!=='pkg'?'flex':'none';$('#modalBootMode').value=g.ps4_boot_mode||'auto';$('#modalPlay').textContent=g.kind==='pkg'?'📦 Instalar PKG':'▶ Jogar';$('#gameModal').classList.add('open')}
async function playSelected(){if(!state.selected)return;try{const r=await post('/api/launch',{id:state.selected.id});if(r.job){location.href='/import.html?job='+encodeURIComponent(r.job);return}toast(`Iniciado com ${r.engine} (PID ${r.pid}).`);$('#gameModal').classList.remove('open');await refresh()}catch(e){toast(e.message,true)}}
async function syncPs4(){try{const r=await post('/api/sync-ps4');await refresh();toast(`${r.count} jogo(s) PS4 sincronizado(s).`)}catch(e){toast(e.message,true)}}
async function openPkgInstaller(){location.href='/import.html'}
async function favSelected(){if(!state.selected)return;try{const r=await post('/api/favorite',{id:state.selected.id});state.selected=r.game;await refresh();openGame(r.game.id)}catch(e){toast(e.message,true)}}
async function saveGameProfile(){if(!state.selected)return;try{const r=await post('/api/game-profile',{id:state.selected.id,profile:$('#modalProfile').value});state.selected=r.game;const i=state.library.findIndex(g=>g.id===r.game.id);if(i>=0)state.library[i]=r.game;toast('Perfil por jogo salvo.')}catch(e){toast(e.message,true)}}
async function saveBootMode(){if(!state.selected)return;try{const r=await post('/api/game-boot-mode',{id:state.selected.id,mode:$('#modalBootMode').value});state.selected=r.game;const i=state.library.findIndex(g=>g.id===r.game.id);if(i>=0)state.library[i]=r.game;toast('Modo de boot PS4 salvo.')}catch(e){toast(e.message,true)}}
async function removeSelected(){if(!state.selected||!confirm(`Remover “${state.selected.title}” da biblioteca? O arquivo do jogo NÃO será apagado.`))return;try{await post('/api/remove',{id:state.selected.id});$('#gameModal').classList.remove('open');await refresh();toast('Removido da biblioteca.')}catch(e){toast(e.message,true)}}
async function openSelectedFolder(){if(!state.selected)return;try{await post('/api/open-folder',{path:state.selected.path})}catch(e){toast(e.message,true)}}
async function verify(){try{const r=await post('/api/verify');const missing=r.checked.filter(x=>!x.exists).length;toast(missing?`${missing} caminho(s) da biblioteca não existem mais.`:'Biblioteca verificada. Todos os caminhos existem.',!!missing)}catch(e){toast(e.message,true)}}
async function clean(){try{const r=await post('/api/clean-cache');toast(`Cache da UX limpo (${fmtBytes(r.removed)} removidos).`)}catch(e){toast(e.message,true)}}
async function loadLogs(){try{const logs=await api('/api/logs');$('#logsList').innerHTML=logs.length?logs.map(l=>`<div class="log-row"><span>${escapeHtml(l.name)}</span><b>${fmtBytes(l.size)}</b></div>`).join(''):'<div class="empty">Nenhum log de execução ainda.</div>'}catch(e){toast(e.message,true)}}

const on=(selector,event,fn)=>{const el=$(selector);if(el)el.addEventListener(event,fn)};
$$('.nav-item').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('[data-page-jump]').forEach(b=>b.onclick=()=>showPage(b.dataset.pageJump));on('#exploreBtn','click',()=>showPage('library'));on('#search','input',e=>{state.query=e.target.value;renderLibrary()});on('#clearSearch','click',()=>{$('#search').value='';state.query='';renderLibrary()});
['#importFileLib','#importPkg','#importQuick'].forEach(s=>on(s,'click',()=>doImport('file')));['#importFolderLib','#importFolder'].forEach(s=>on(s,'click',()=>doImport('folder')));['#scanCusaLib','#scanCusa'].forEach(s=>on(s,'click',scanCusa));['#syncPs4Lib','#syncPs4Lib2'].forEach(s=>on(s,'click',syncPs4));on('#openPkgInstaller','click',openPkgInstaller);on('#openPkgInstallerSettings','click',openPkgInstaller);on('#saveSettings','click',saveSettings);on('#applyProfile','click',applyProfile);on('#performanceProfile','change',updateProfileHint);on('#gpuIndex','change',updateGpuHint);on('#refreshStatus','click',refresh);on('#probeVulkan','click',probeVulkan);on('#runDiagnostics','click',runDiagnostics);on('#openPipelineCache','click',openPipelineCache);on('#closeModal','click',()=>$('#gameModal').classList.remove('open'));on('#gameModal','click',e=>{if(e.target.id==='gameModal')e.currentTarget.classList.remove('open')});on('#modalPlay','click',playSelected);on('#modalProfile','change',saveGameProfile);on('#modalBootMode','change',saveBootMode);on('#modalFavorite','click',favSelected);on('#modalRemove','click',removeSelected);on('#modalFolder','click',openSelectedFolder);on('#verifyBtn','click',verify);on('#cleanCacheBtn','click',clean);on('#openPS5','click',()=>post('/api/open-engine',{engine:'kyty'}).catch(e=>toast(e.message,true)));on('#openPS4','click',()=>post('/api/open-engine',{engine:'shadps4'}).catch(e=>toast(e.message,true)));
document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#gameModal').classList.remove('open')});
refresh();setInterval(async()=>{try{state.status=await api('/api/status');renderStatus()}catch{}},15000);
