#!/usr/bin/env python3
"""Full-tree static audit for PKG_DoW/KytyPS5.
Reads every regular file, hashes it, classifies text/binary, and records implementation markers.
No source file is skipped except generated audit output itself when rerun.
"""
from __future__ import annotations
import hashlib, json, os, re, sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "repo_audit.json"
SKIP = {OUT.resolve()}
TEXT_EXT = {'.c','.cc','.cpp','.cxx','.h','.hh','.hpp','.inl','.inc','.cmake','.txt','.md','.json','.yml','.yaml','.xml','.py','.ps1','.bat','.sh','.comp','.vert','.frag','.glsl','.toml','.ini','.cfg','.lua','.natvis','.clang-format','.gitignore'}
MARKERS = {
    'exit_not_implemented': re.compile(rb'EXIT_NOT_IMPLEMENTED'),
    'not_implemented': re.compile(rb'not implemented|unimplemented', re.I),
    'todo_fixme': re.compile(rb'\b(?:TODO|FIXME|XXX)\b', re.I),
    'assert_exit': re.compile(rb'EXIT_IF|EXIT\('),
}

def is_probably_text(path: Path, data: bytes) -> bool:
    if path.suffix.lower() in TEXT_EXT or path.name in {'CMakeLists.txt','LICENSE','README'}:
        return True
    if b'\0' in data[:8192]:
        return False
    try:
        data[:65536].decode('utf-8')
        return True
    except UnicodeDecodeError:
        return False

def area_for(rel: str) -> str:
    parts = rel.split('/')
    if rel.startswith('src/graphics/shader'): return 'graphics/shader'
    if rel.startswith('src/graphics/guest_gpu'): return 'graphics/guest_gpu'
    if rel.startswith('src/graphics/host_gpu'): return 'graphics/host_gpu'
    if rel.startswith('src/graphics/presentation'): return 'graphics/presentation'
    if rel.startswith('src/kernel'): return 'kernel'
    if rel.startswith('src/libs'): return 'libs'
    if rel.startswith('src/loader'): return 'loader'
    if rel.startswith('src/launcher'): return 'launcher'
    if rel.startswith('src/common'): return 'common'
    if rel.startswith('tests'): return 'tests'
    if rel.startswith('3rdparty'): return '3rdparty'
    return parts[0] if parts else 'root'

records=[]
exts=Counter(); areas=defaultdict(Counter); total_bytes=0
for p in sorted(ROOT.rglob('*')):
    if not p.is_file() or p.resolve() in SKIP:
        continue
    # Exclude only transient build outputs generated by this analysis, not checked-in project files.
    rel=p.relative_to(ROOT).as_posix()
    if rel.startswith('_Build/ci/'):
        continue
    try:
        data=p.read_bytes()
    except OSError as e:
        records.append({'path':rel,'error':str(e)})
        continue
    total_bytes += len(data)
    ext=p.suffix.lower() or '<none>'
    exts[ext]+=1
    text=is_probably_text(p,data)
    counts={name: len(rx.findall(data)) for name,rx in MARKERS.items()} if text else {name:0 for name in MARKERS}
    area=area_for(rel)
    areas[area]['files']+=1
    areas[area]['bytes']+=len(data)
    for k,v in counts.items(): areas[area][k]+=v
    records.append({
        'path':rel, 'size':len(data), 'sha256':hashlib.sha256(data).hexdigest(),
        'text':text, 'extension':ext, 'area':area, **counts
    })

out={
  'root':'.', 'files_read':len(records), 'bytes_read':total_bytes,
  'extensions':dict(exts.most_common()),
  'areas':{k:dict(v) for k,v in sorted(areas.items())},
  # All-text totals are useful for reproducing the raw scan, but generated documentation can quote
  # implementation markers. Keep source-only totals separate so the technical debt metric does not
  # grow merely because this report discusses it.
  'marker_totals':{m:sum(r.get(m,0) for r in records) for m in MARKERS},
  'source_marker_totals':{
      m:sum(r.get(m,0) for r in records if r.get('path','').startswith('src/'))
      for m in MARKERS
  },
  'files':records,
}
OUT.write_text(json.dumps(out,indent=2),encoding='utf-8')
print(json.dumps({k:out[k] for k in ('files_read','bytes_read','marker_totals')},indent=2))
print(f'wrote {OUT}')
